version: '3.4'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"          
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: yourapp
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser!
    volumes:
      - mysqldata:/var/lib/mysql
  yourapp:
    image: ${DOCKER_REGISTRY-}yourapp
    build:
      context: .
      dockerfile: Yourapp/Dockerfile    
    depends_on:
      - db
volumes:
    mysqldata:
        driver: local